### ISSUE TITLE
Stream Quality max at 720

### ISSUE THREAD

**Issue by RHStonks** [chamchenko/plugin.video.nbainternational#12]
Weird issue happening with my Android tablet as max quality is 720 whereas on my Mi Box can get 1080. 

Other addons on my Android tablet can get 1080 so not sure why this issue is happening with the NBA International kodi addon.

**Comment by chamchenko** [comment]
This question have been answered in the kodi forum [here](https://forum.kodi.tv/showthread.php?tid=362466&pid=3082984#pid3082984)

**Comment by RHStonks** [comment]
Thanks. Problem solved.
