### ISSUE TITLE
Feature request: include game summaries in archive

### ISSUE THREAD

**Issue by nre-ableton** [chamchenko/plugin.video.nbainternational#16]
One feature that I miss from the old NBA plugin (and the only reason that I keep the old plugin installed) is the ability to watch the short game summaries. The old plugin put them in the game archive next to the other camera feeds. The NBA international plugin *does* include feeds for the condensed games and highlights, but not the summaries.

Just to be clear, the summaries are the 2-3 minute video recaps with a narrator who briefly summarizes what happened in the game. I prefer watching these to the condensed games, since if I need to catch up on ~10 games, it's impractical to watch the condensed games that tend to be around 10-20 minutes.

Otherwise this plugin is absolutely great! Keep up the good work!

**Comment by chamchenko** [comment]
If I'm not wrong short game summaries were in the Videos Collections section last season. Last time I checked this section of the add-on was not working and I need to find the time to fix it. maybe next week-end but I can't promise that. If I do it I will post a reply here to ask to check.

**Comment by nre-ableton** [comment]
No rush, just a "nice to have" feature. Thanks for looking into it!

**Comment by chamchenko** [comment]
Hi @nre-ableton I've just submitted a temporary fix for the Videos Collection section. You can find all the game summaries in that section under GAME RECAPS.

**Comment by nre-ableton** [comment]
@chamchenko Great, thanks! Will you make a new release soon?

**Comment by chamchenko** [comment]
@nre-ableton Yes I released an update it is available on my repository.

**Comment by nre-ableton** [comment]
I updated the add-on this weekend and it works great! Thanks for adding this. 👍
