### ISSUE TITLE
Live Game Crash

### ISSUE THREAD

**Issue by scottydulton** [chamchenko/plugin.video.nbainternational#2]
Crashed while watching live game today

[kodi.old.log](https://github.com/chamchenko/plugin.video.nbainternational/files/6529319/kodi.old.log)

**Comment by scottydulton** [comment]
and again now
[kodi.log](https://github.com/chamchenko/plugin.video.nbainternational/files/6529395/kodi.log)
@chamchenko

**Comment by chamchenko** [comment]
Hi @scottydulton I'm seeing this from my phone so I can't really look closer into the log ( will do it later) just wanted to know if the crash happens at the start of playback or after a while

**Comment by scottydulton** [comment]
@chamchenko  after a while today mate

**Comment by chamchenko** [comment]
Did this happen only on windows or on android too, just to confirm it's a hard kodi crash not only a playback crash?

**Comment by scottydulton** [comment]
only on windows, i will test on both platforms today, game starts in an hour

**Comment by scottydulton** [comment]
@chamchenko turns out on windows it was a conflicting add-on, when disabled that add-on it ran perfect, FYI, i played around with the 120 second delay time on multiple values on both windows and firestick, i ended up deleting the delay all together and tested and both ran flawless with no delay whatsoever

**Comment by chamchenko** [comment]
Hi @scottydulton , glad it worked. you can keep this open for few days just in case. It would also be helpful if you stated the add-on full name and id. So we can keep traceability for other users.
Otherwise for the 120 second delay, I'm planning to removed it, just didn't had time for the last few days.

**Comment by scottydulton** [comment]
@chamchenko yes i will test tomorrow, i didnt have time to work out whether it was a problem with my build or which exact add-on was the cause, i literally just disabled every other add-on so will eliminate 1 by 1 over the next few days and edit my comments :)
And yep was just providing you feedback regarding delay that i had tested 2 full games on 2 platforms to save you doing it :)

**Comment by chamchenko** [comment]
@scottydulton Thank you for the initiative.
