### ISSUE TITLE
AmbiguisTimeError

### ISSUE THREAD

**Issue by RHStonks** [chamchenko/plugin.video.nbainternational#9]
Hi Chamchenko, 

Today there has been an issue with the addon. When I go into games and click on live games it pops up with an error "AmbiguisTimeError". 

Does the addon need to be updated?

**Comment by chamchenko** [comment]
> Hi Chamchenko,
> 
> Today there has been an issue with the addon. When I go into games and click on live games it pops up with an error "AmbiguisTimeError".
> 
> Does the addon need to be updated?

Whithout log I have no way to know what's going wrong, but just a guess did you check the time on your device is it correct?

**Comment by RHStonks** [comment]
> > Hi Chamchenko,
> 
> > 
> 
> > Today there has been an issue with the addon. When I go into games and click on live games it pops up with an error "AmbiguisTimeError".
> 
> > 
> 
> > Does the addon need to be updated?
> 
> 
> 
> Whithout log I have no way to know what's going wrong, but just a guess did you check the time on your device is it correct?

Forgot to mention that it worked like an hour later for some reason not sure why.
